import streamlit as st
import pandas as pd
import random


def generate_random_data():
    dummy_users_list = {
        'user_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'user_name': ['user1', 'user2', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10'],
        'user_email': ['user1@example.com', 'user2@example.com', 'user3@example.com', 'user4@example.com', 'user5@example.com', 'user6@example.com', 'user7@example.com', 'user8@example.com', 'user9@example.com', 'user10@example.com'],
        'user_password': ['user1', 'user2', 'user3', 'user4', 'user5', 'user6', 'user7', 'user8', 'user9', 'user10'],
        'user_age': [random.randint(18, 60) for _ in range(10)],
        'user_gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
        'user_city': [random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston']) for _ in range(10)]
    }

    users_df = pd.DataFrame(dummy_users_list)
    random_user = users_df.sample(n=1).iloc[0]

    topics = ['sports', 'music', 'movies', 'technology', 'art', 'science', 'history', 'travel', 'food', 'fashion']
    random_topics = random.sample(topics, k=5)

    pages = [f'page_{i}' for i in range(1, 21)]
    random_page = random.choice(pages)
    url = f"http://{random_page}.com"

    return random_user, random_topics, url
interest = "interest"
def creative_demo_page():
    st.title("Creative Demo Page")
    st.write("Welcome to the Creative Demo page!")

    if 'user_input' in st.session_state:

        st.write(f"User-provided URL: {st.session_state.user_input}")
        random_user, random_topics, random_url = generate_random_data()
        st.write("# Advertisment")
        st.write("----Promp----")
        st.write(f'''create an image base on this topic :{st.write(', '.join(random_topics))}
                 for this website{st.session_state.user_input}
                 for a user of age{random_user['user_age']} of gender: {random_user['user_gender']}
                 that lives in the city of: {random_user['user_city']}.That is interested in
                 {interest}''')

        st.write(" image generated by AI")

        st.write(" Recommended websites,alternative websites for add placement")
        st.write(random_url)

    if st.button("Go Back to Main Page", key='back_to_main_demo'):
        st.session_state.page = 'main'
